// sign up
export const SIGNUP_BEGIN = "SIGNUP_BEGIN";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

// OTP
export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// Available Timings
export const AVILABLE_TABLE_BEGIN = "AVILABLE_TABLE_BEGIN";
export const AVILABLE_TABLE_SUCCESS = "AVILABLE_TABLE_SUCCESS";
export const AVILABLE_TABLE_FAIL = "AVILABLE_TABLE_FAIL";

// total table
export const TOTLE_TABLE_BEGIN = "TOTLE_TABLE_BEGIN";
export const TOTLE_TABLE_SUCCESS = "TOTLE_TABLE_SUCCESS";
export const TOTLE_TABLE_FAIL = "TOTLE_TABLE_FAIL";

// Logout user
export const LOGOUT_USER = "LOGIN_FAIL";

// Edit Profile
export const EDIT_PROFILE_BEGIN = "EDIT_PROFILE_BEGIN";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_ERROR = "EDIT_PROFILE_ERROR";

// Notification
export const GET_NOTIFICATION_BEGIN = "GET_NOTIFICATION_BEGIN";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_ERROR = "GET_NOTIFICATION_ERROR";

// Create Oreder
export const CREATE_ORDER_BEGIN = "CREATE_ORDER_BEGIN";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";

// Update Oreder
export const UPDATE_ORDER_BEGIN = "UPDATE_ORDER_BEGIN";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_ERROR = "UPDATE_ORDER_ERROR";

// Send OTP
export const SEND_OTP_BEGIN = "SEND_OTP_BEGIN";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_ERROR = "SEND_OTP_ERROR";

// check otp

export const CHECK_OTP_BEGIN = "CHECK_OTP_BEGIN";
export const CHECK_OTP_SUCCESS = "CHECK_OTP_SUCCESS";
export const CHECK_OTP_ERROR = "CHECK_OTP_ERROR";

// check otp

export const NEW_PASSWORD_BEGIN = "NEW_PASSWORD_BEGIN";
export const NEW_PASSWORD_SUCCESS = "NEW_PASSWORD_SUCCESS";
export const NEW_PASSWORD_ERROR = "NEW_PASSWORD_ERROR";

// Counter List

export const COUNTER_LIST_BEGIN = "COUNTER_LIST_BEGIN";
export const COUNTER_LIST_SUCCESS = "COUNTER_LIST_SUCCESS";
export const COUNTER_LIST_ERROR = "COUNTER_LIST_ERROR";

// Order Category

export const ORDER_CATEGORY_BEGIN = "ORDER_CATEGORY_BEGIN";
export const ORDER_CATEGORY_SUCCESS = "ORDER_CATEGORY_SUCCESS";
export const ORDER_CATEGORY_ERROR = "ORDER_CATEGORY_ERROR";

// Order Item

export const ORDER_ITEM_BEGIN = "ORDER_ITEM_BEGIN";
export const ORDER_ITEM_SUCCESS = "ORDER_ITEM_SUCCESS";
export const ORDER_ITEM_ERROR = "ORDER_ITEM_ERROR";

// Place Order

export const PLACE_ORDER_BEGIN = "PLACE_ORDER_BEGIN";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_ERROR = "PLACE_ORDER_ERROR";

// Order List

export const ORDER_LIST_BEGIN = "ORDER_LIST_BEGIN";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_ERROR = "ORDER_LIST_ERROR";

// cart

export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT";
